name: node.js build

on:
  push:
    branches: [ master ]

env:
  # github.repository as <account>/<repo>
  DOCKERHUB_USER: antoineaumjaud
  IMAGE_NAME: antoineaumjaud/api-family
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build-config
    - run: npm test

    # Login against a Docker
    # https://github.com/docker/login-action
    - name: Log into Docker registry 
      uses: docker/login-action@v2.0.0
      with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: ${{ env.IMAGE_NAME }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
