name: node.js build

on: push

env:
  DOCKERHUB_USER: antoineaumjaud
  IMAGE_NAME: antoineaumjaud/api-family
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build-config
    - run: npm test

    # Login against a Docker
    # https://github.com/docker/login-action
    - name: Log into Docker registry 
      if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
      uses: docker/login-action@v2.0.0
      with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        tags: ${{ env.IMAGE_NAME }}:latest
        push: true

  notification:
    if: always()
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Webhook
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://api-synology-chatbot.aumjaud.fr/secure/send-message/continuous-integration
        method: POST
        customHeaders: '{"secure-key": "${{ secrets.API_CHATBOT_TOKEN }}", "content-type": "application/json"}'
        data: '{"message": "${{ job.status && "Build successful" || "Build failed" }} of ${{ github.repository }}", "url": "${{ github.repositoryUrl }}"}'
